version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_HOST=595508394202.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=$REPOSITORY_HOST/syn-bungee-servers
      - aws ecr get-login-password  | docker login --username AWS --password-stdin $REPOSITORY_HOST
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Compile jars started on `date`
      - mvn clean package -P package-all
      - echo Building the Docker image...
      - echo running docker build
      - docker build -t $REPOSITORY_URI:latest .
      - echo not tagging with $REPOSITORY_URI:latest with $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - aws ecs update-service --region us-west-2 --cluster SyndicateECSCluster --service arn:aws:ecs:us-west-2:595508394202:service/SyndicateECSCluster/SyndicateBungeeECSServiceV03 --force-new-deployment
artifacts:
  files:
    - "**/target/*"
  discard-paths: yes
